# Check that syntax is correct

name: CIFSyntaxandStyleCheck

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  syntax:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: checkout
          uses: actions/checkout@v2
          
      # Check syntax of all CIF files
        - name: check_syntax
          uses: COMCIFS/cif_syntax_check_action@master
          id: cif_syntax_check
  ddlm:
    runs-on: ubuntu-latest
    needs: syntax
    steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: check_ddlm
          uses: jamesrhester/dictionary_check_action@main
          id: ddlm_check
